name: Run Python script and update Gist

on:
  schedule:
    - cron: '0 3 * * *' # Runs at 03:00 AM (UTC) daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python script.py
